
management:
  endpoint:
    beans:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1064MB
  cloud:
    consul:
      discovery:
        register-health-check: false
        hostname: localhost
    stream:
      bindings:
        new-utilisateur:
          destination: messages
          group: utilisateur.new
          binder: rabbit
          producer:
            requiredGroups: ${spring.cloud.stream.bindings.new-utilisateur.group}
            routingKeyExpression: 'messages.utilisateur.new'
            bindingRoutingKey: messages.utilisateur.new
        register-utilisateur:
          destination: messages
          group: utilisateur.register
          binder: rabbit
          producer:
            requiredGroups: ${spring.cloud.stream.bindings.register-utilisateur.group}
            routingKeyExpression: 'messages.utilisateur.register'
            bindingRoutingKey: messages.utilisateur.register
        delete-utilisateur:
          destination: messages
          group: utilisateur.delete
          binder: rabbit
          producer:
            requiredGroups: ${spring.cloud.stream.bindings.delete-utilisateur.group}
            routingKeyExpression: 'messages.utilisateur.delete'
            bindingRoutingKey: messages.utilisateur.delete
        update-utilisateur:
          destination: messages
          group: utilisateur.update
          binder: rabbit
          producer:
            requiredGroups: ${spring.cloud.stream.bindings.update-utilisateur.group}
            routingKeyExpression: 'messages.utilisateur.update'
            bindingRoutingKey: messages.utilisateur.update
        episode-utilisateur:
          destination: messages
          group: utilisateur.episode
          binder: rabbit
          producer:
            requiredGroups: ${spring.cloud.stream.bindings.episode-utilisateur.group}
            routingKeyExpression: 'messages.utilisateur.episode'
            bindingRoutingKey: messages.utilisateur.episode
        patch-utilisateur:
          destination: messages
          group: utilisateur.patch
          binder: rabbit
          producer:
            requiredGroups: ${spring.cloud.stream.bindings.patch-utilisateur.group}
            routingKeyExpression: 'messages.utilisateur.patch'
            bindingRoutingKey: messages.utilisateur.patch
        new-cours:
          destination: messages
          group: cours.new
          binder: rabbit
          producer:
            requiredGroups: ${spring.cloud.stream.bindings.new-cours.group}
            routingKeyExpression: 'messages.cours.new'
            bindingRoutingKey: messages.cours.new
        update-cours:
          destination: messages
          group: cours.update
          binder: rabbit
          producer:
            requiredGroups: ${spring.cloud.stream.bindings.update-cours.group}
            routingKeyExpression: 'messages.cours.update'
            bindingRoutingKey: messages.cours.update
        patch-cours:
          destination: messages
          group: cours.patch
          binder: rabbit
          producer:
            requiredGroups: ${spring.cloud.stream.bindings.patch-cours.group}
            routingKeyExpression: 'messages.cours.patch'
            bindingRoutingKey: messages.cours.patch
        delete-cours:
          destination: messages
          group: cours.delete
          binder: rabbit
          producer:
            requiredGroups: ${spring.cloud.stream.bindings.delete-cours.group}
            routingKeyExpression: 'messages.cours.delete'
            bindingRoutingKey: messages.cours.delete
        new-episode:
          destination: messages
          group: episode.new
          binder: rabbit
          producer:
            requiredGroups: ${spring.cloud.stream.bindings.new-episode.group}
            routingKeyExpression: 'messages.episode.new'
            bindingRoutingKey: messages.episode.new
        update-episode:
          destination: messages
          group: episode.update
          binder: rabbit
          producer:
            requiredGroups: ${spring.cloud.stream.bindings.update-episode.group}
            routingKeyExpression: 'messages.episode.update'
            bindingRoutingKey: messages.episode.update
        patch-episode:
          destination: messages
          group: episode.patch
          binder: rabbit
          producer:
            requiredGroups: ${spring.cloud.stream.bindings.patch-episode.group}
            routingKeyExpression: 'messages.episode.patch'
            bindingRoutingKey: messages.episode.patch
        delete-episode:
          destination: messages
          group: episode.delete
          binder: rabbit
          producer:
            requiredGroups: ${spring.cloud.stream.bindings.delete-episode.group}
            routingKeyExpression: 'messages.episode.delete'
            bindingRoutingKey: messages.episode.delete

---
spring:
  profiles: docker
  cloud:
    consul:
      host: consul
      discovery:
        hostname: consul
  rabbitmq:
    host: rabbitmq
